### ISSUE TITLE
Can someone add example for Object Types ? 

### ISSUE THREAD

**Issue by dschandrasekara** [dschandrasekara/learn-typescript#105]
Ref : https://www.w3schools.com/typescript/typescript_object_types.php

**Comment by rupak2001** [comment]
can i contribute to this issue ??
in which folder should i put the code ??

**Comment by dschandrasekara** [comment]
can u create new folder objectType and include ur ts inside of it. ?

**Comment by rupak2001** [comment]
alright

**Comment by dschandrasekara** [comment]
#109
