### ISSUE TITLE
Can someone add RegExp examples ? 

### ISSUE THREAD

**Issue by dschandrasekara** [dschandrasekara/learn-typescript#42]
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

**Comment by callam20** [comment]
I can take this up

**Comment by dschandrasekara** [comment]
@callam20 sure let's do it

**Comment by droidttk** [comment]
@dschandrasekara let me work on this

**Comment by dschandrasekara** [comment]
@droidttk sure lets do it
